version: '3.8'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

  vote-api:
    build: ./vote-api
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
    depends_on:
      - redis
      - mongo
    ports:
      - "8000:8000"

  result-api:
    build: ./result-api
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
      - ADMIN_EMAIL=lelesachit@gmail.com # Add this line
    depends_on:
      - redis
      - mongo
    ports:
      - "8001:8000"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes: # Optional: persist mongo data
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourstrongpassword # Change in production
      MYSQL_DATABASE: votelogin_db
      MYSQL_USER: voteuser
      MYSQL_PASSWORD: votepassword # Change in production
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-api: # Handles authentication and token generation
    build: ./auth-api # You will need to create this service
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=voteuser
      - DB_PASSWORD=votepassword
      - DB_NAME=votelogin_db
      - JWT_SECRET=yoursupersecretkey # Change in production
    depends_on:
      - mysql
    ports:
      - "8002:8000" # Example port, ensure it's unique on the host

volumes:
  mysql_data:
  mongo_data: # If you added a volume for mongo
