apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  namespace: voting-app
  labels:
    app: mysql
data:
  init.sql: |
    USE votelogin_db;

    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        role ENUM('user', 'admin') NOT NULL
    );

    INSERT INTO users (username, password, role) VALUES ('testuser', 'userpass123', 'user') ON DUPLICATE KEY UPDATE password=VALUES(password), role=VALUES(role);
    INSERT INTO users (username, password, role) VALUES ('admin01', 'adminpass123', 'admin') ON DUPLICATE KEY UPDATE password=VALUES(password), role=VALUES(role);
    