apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: voting-app
  labels:
    app: auth-api
spec:
  selector:
    app: auth-api
  ports:
  - protocol: TCP
    port: 8000       
    targetPort: 8000 
  type: NodePort     
