apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80            # Port other services might use (if any) or internal LB port
    targetPort: 80      # Port the Nginx container is listening on
    nodePort: 30080     # Exposes on NodeIP:30080 (similar to 8080:80)
  type: NodePort        