apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy ensures that container images are only pulled from approved
      Docker Hub repositories. It allows images from the official Docker Hub library
      (e.g., 'nginx', 'redis') and a specific list of user/organization accounts.
      All other registries and accounts are blocked.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-docker-hub-images
      match:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - voting-app
      validate:
        message: "Image registry is not approved. Only official Docker Hub and specific user accounts (sachitlele, jenkins, mysql) are allowed."
        anyPattern:
        - image: "docker.io/sachitlele/*"   
        - image: "docker.io/shreyasr03/*"      
        - image: "docker.io/jenkins/*"      
        - image: "docker.io/mysql/*"        
        - image: "docker.io/library/*"    