apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-manual
  labels:
    type: local
spec:
  storageClassName: "" 
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo" 
  persistentVolumeReclaimPolicy: Retain