apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-manual # You can name this PV anything
  labels:
    type: local # Optional label
spec:
  storageClassName: "" # Important: Empty string for manual binding if PVC doesn't specify one
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data/mysql" 
  persistentVolumeReclaimPolicy: Retain 