apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-manual 
  labels:
    type: local 
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: "/mnt/data/mysql" 
  persistentVolumeReclaimPolicy: Retain 