apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-api
  namespace: voting-app
  labels:
    app: result-api
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: result-api
  template:
    metadata:
      labels:
        app: result-api
    spec:
      imagePullSecrets:
      - name: my-docker-hub-credentials  
      containers:
      - name: result-api
        image: sachitlele/voteapp-result-api:latest 
        ports:
        - containerPort: 8000 
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MONGO_HOST
          value: "mongo"
        - name: ADMIN_EMAIL
          value: "lelesachit@gmail.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"