apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-api
  namespace: voting-app
  labels:
    app: result-api
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: result-api
  template:
    metadata:
      labels:
        app: result-api
    spec:
      containers:
      - name: result-api
        image: sachitlele/voteapp-result-api:latest # YOUR ACTUAL IMAGE
        ports:
        - containerPort: 8000 # Internal port the app listens on
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MONGO_HOST
          value: "mongo"
        - name: ADMIN_EMAIL
          value: "lelesachit@gmail.com"
        # Consider moving ADMIN_EMAIL to a ConfigMap if it changes per environment
        resources: # It's good practice to add these!
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"