apiVersion: v1
kind: Service
metadata:
  name: result-api
  namespace: voting-app
  labels:
    app: result-api
spec:
  selector:
    app: result-api
  ports:
  - protocol: TCP
    port: 8000        
    targetPort: 8000  
    nodePort: 30001   
  type: NodePort