apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-api
  labels:
    app: result-api
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: result-api
  template:
    metadata:
      labels:
        app: result-api
    spec:
      containers:
      - name: result-api
        image: your-repo/result-api:latest # Replace with your actual image
        ports:
        - containerPort: 8000 # Internal port the app listens on
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MONGO_HOST
          value: "mongo"
        - name: MYSQL_HOST
          value: "mysql" # Kubernetes service name for MySQL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: mysql-password
        - name: MYSQL_DB_NAME # Or whatever your app expects for the database name
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: mysql-database
        - name: ADMIN_EMAIL
          value: "lelesachit@gmail.com"
        resources: # It's good practice to add these!
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"