apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-api
  labels:
    app: result-api
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: result-api
  template:
    metadata:
      labels:
        app: result-api
    spec:
      containers:
      - name: result-api
        image: your-repo/result-api:latest # Replace with your actual image
        ports:
        - containerPort: 8000 # Internal port the app listens on
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: MONGO_HOST
          value: "mongo"
        - name: ADMIN_EMAIL
          value: "lelesachit@gmail.com"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/firebase/service-account.json"
        volumeMounts:
        - name: firebase-secret-volume
          mountPath: "/etc/firebase"
          readOnly: true
      volumes:
      - name: firebase-secret-volume
        secret:
          secretName: firebase-creds