apiVersion: v1
kind: Service
metadata:
  name: vote-api
spec:
  selector:
    app: vote-api
  ports:
  - protocol: TCP
    port: 8000        # Internal port
    targetPort: 8000  # Container port
    nodePort: 30000   # Exposes on NodeIP:30000 (similar to 8000:8000)
  type: NodePort 