apiVersion: v1
kind: Service
metadata:
  name: vote-api
  namespace: voting-app
  labels:
    app: vote-api
spec:
  selector:
    app: vote-api
  ports:
  - protocol: TCP
    port: 8000       
    targetPort: 8000  
    nodePort: 30000   
  type: NodePort 