apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-api
  namespace: voting-app
  labels:
    app: vote-api
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: vote-api
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      containers:
      - name: vote-api
        image: sachitlele/voteapp-vote-api:latest 
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis" 
        - name: MONGO_HOST
          value: "mongo" 
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets 
              key: JWT_SECRET
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"