apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-redis
  namespace: voting-app 
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: vote-api
    - podSelector:
        matchLabels: 
          app: result-api

    ports: 
    - protocol: TCP
      port: 6379
