apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
  labels:
    app: mysql
data:
  init-db.sql: |
    -- This script will run after the MySQL container has initialized the database
    -- and user specified by MYSQL_DATABASE, MYSQL_USER, and MYSQL_PASSWORD environment variables.

    -- The MySQL client executing this script is typically already connected to the
    -- database specified by the MYSQL_DATABASE environment variable.

    CREATE TABLE IF NOT EXISTS credentials (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        password_hash VARCHAR(255) NOT NULL, -- IMPORTANT: Store securely hashed passwords!
        role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'user')),
        INDEX(username)
    );

    INSERT IGNORE INTO credentials (username, password_hash, role)
    VALUES ('admin', 'your_securely_hashed_admin_password', 'admin'); -- TODO: Replace hash

    INSERT IGNORE INTO credentials (username, password_hash, role)
    VALUES ('user', 'your_securely_hashed_user_password', 'user'); -- TODO: Replace hash