apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306        # Port other services in the cluster will use to connect
    targetPort: 3306   # Port the MySQL container is listening on
  # type: ClusterIP is the default and usually what you want for internal DBs